# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.box_version = "12.20240905.1"

  config.vm.define "gbudauS" do |control|
    control.vm.hostname = "gbudauS"
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
    control.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update -y
      sudo apt-get install -y curl

      curl -sfL https://get.k3s.io | sh -s - --node-ip=192.168.56.110 --write-kubeconfig-mode "0644"

      # Wait until the K3s node is fully ready
      while [[ $(kubectl get nodes -o jsonpath='{.items[*].status.conditions[?(@.type=="Ready")].status}') != "True" ]]; do
        echo "Waiting for K3s to fully start..."
        sleep 5
      done

      export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
      kubectl apply -f /vagrant/confs/app1/app1.yaml
      kubectl apply -f /vagrant/confs/app2/app2.yaml
      kubectl apply -f /vagrant/confs/app3/app3.yaml
    SHELL
  end
end
