# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.box_version = "12.20240905.1"

  config.vm.define "gbudauS" do |server|
    server.vm.hostname = "gbudauS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
    server.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update -y
      sudo apt-get install -y curl

      curl -sfL https://get.k3s.io | sh -s - --node-ip=192.168.56.110 --write-kubeconfig-mode "0644"
      mkdir -p /vagrant/shared
      cp /var/lib/rancher/k3s/server/node-token /vagrant/shared/k3s_token
    SHELL
  end

  config.vm.define "gbudauSW" do |worker|
    worker.vm.hostname = "gbudauSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = 1
    end
    worker.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update -y
      sudo apt-get install -y curl

      while [ ! -f /vagrant/shared/k3s_token ];
        do sleep 1;
      done

      K3S_TOKEN=$(cat /vagrant/shared/k3s_token)
      curl -sfL https://get.k3s.io | K3S_URL=https://192.168.56.110:6443 K3S_TOKEN=${K3S_TOKEN} sh -s - --node-ip=192.168.56.111 --write-kubeconfig-mode "0644"
    SHELL
  end
end
