# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.box_version = "20241002.0.0"

  config.vm.define "gbudauS" do |control|
    control.vm.hostname = "gbudauS"
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
    control.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update -y
      sudo apt-get install -y curl

      curl -sfL https://get.k3s.io | sh -s - --node-ip=192.168.56.110 --write-kubeconfig-mode "0644"
      mkdir -p /vagrant/shared
      cp /var/lib/rancher/k3s/control/node-token /vagrant/shared/k3s_token
    SHELL
  end

  config.vm.define "gbudauSW" do |control|
    control.vm.hostname = "gbudauSW"
    control.vm.network "private_network", ip: "192.168.56.111"
    control.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = 1
    end
    control.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update -y
      sudo apt-get install -y curl

      while [ ! -f /vagrant/shared/k3s_token ];
        do sleep 1;
      done

      K3S_TOKEN=$(cat /vagrant/shared/k3s_token)
      curl -sfL https://get.k3s.io | K3S_URL=https://192.168.56.110:6443 K3S_TOKEN=${K3S_TOKEN} sh -s - --node-ip=192.168.56.111
    SHELL
  end
end
