# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.box_version = "12.20240905.1"

  config.vm.define "gbudauS" do |control|
    control.vm.hostname = "gbudauS"
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
    control.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update -y
      sudo apt-get install -y curl
 
      K3S_TOKEN=$(cat /vagrant/confs/.k3s_token)
      curl -sfL https://get.k3s.io | K3S_TOKEN=${K3S_TOKEN} sh -s - --node-ip=192.168.56.110 --write-kubeconfig-mode "0644"
    SHELL
  end

  config.vm.define "gbudauSW" do |control|
    control.vm.hostname = "gbudauSW"
    control.vm.network "private_network", ip: "192.168.56.111"
    control.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = 1
    end
    control.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update -y
      sudo apt-get install -y curl

      K3S_TOKEN=$(cat /vagrant/confs/.k3s_token)
      curl -sfL https://get.k3s.io | K3S_URL=https://192.168.56.110:6443 K3S_TOKEN=${K3S_TOKEN} sh -s - --node-ip=192.168.56.111
    SHELL
  end
end
